name: C++ CI Pipeline

on:
  push:
    branches:
      - Client_socket
      - feature/*
  pull_request:
    branches:
      - Client_socket

jobs:
  lint-and-build:
    name: Lint, Build, and Test C++ Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck build-essential

      - name: Install Node.js and Commitlint
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Commitlint Dependencies
        run: npm install --save-dev @commitlint/config-conventional @commitlint/cli

      - name: Run Cppcheck
        run: |
          # Adjust this path to the correct src directory if not in the root
          cppcheck --enable=all --std=c++17 --language=c++ --project=compile_commands.json ./src/
          cppcheck --enable=all --std=c++17 --language=c++ ./src/

      - name: Lint Commit Messages
        run: |
          npx --no-install commitlint --from=$(git rev-parse HEAD^)