name: C++ CI Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    name: Lint, Build, and Test C++ Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cppcheck \
            build-essential \
            cmake \
            wget \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            libudev-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libopenal-dev \
            libvorbis-dev \
            libogg-dev \
            libflac-dev \
            libxcursor-dev \
            libfreetype6-dev \
            libcriterion-dev

      - name: Configure the Project
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Lint commit messages
        run: |
          npx commitlint --from=HEAD~10 --to=HEAD

      - name: Run Cppcheck
        run: |
          cppcheck --project=cppcheck-config.json --error-exitcode=1

      - name: Build the Project
        run: |
          cmake --build build

      - name: Run ECS Unit Tests
        run: |
          cmake --build build --target unit_tests
          ./build/ECS/unit_tests
