name: C++ CI Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    name: Lint, Build, and Test C++ Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cppcheck \
            build-essential \
            cmake \
            wget \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            libudev-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libopenal-dev \
            libvorbis-dev \
            libogg-dev \
            libflac-dev \
            libxcursor-dev \
            libfreetype6-dev \
            libcriterion-dev \
            asio-dev

      - name: Run Cppcheck on Client Sources
        run: |
          cppcheck --enable=all --std=c++20 --language=c++ --include=client/include client/src/
      
      - name: Run Cppcheck on ECS Sources
        run: |
          cppcheck --enable=all --std=c++20 --language=c++ --include=ECS/include ECS/src/
      
      - name: Run Cppcheck on Server Sources
        run: |
          cppcheck --enable=all --std=c++20 --language=c++ --include=server/include server/src/

      - name: Configure the Project
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Verify CPM Dependencies
        run: |
          echo "Listing CPM dependencies for verification:"
          ls -la build/_deps/asio-src/asio/include
          ls -la build/_deps/nlohmann_json-src/include

      - name: Build the Project
        run: |
          cmake --build build

      - name: Test Build Targets
        run: |
          cmake --build build --target ecs
          cmake --build build --target client
          cmake --build build --target server
          cmake --build build --target client_2
